security:
  jwt:
    token:
      expire-length: 3600000
      auth-login-url: /users/authenticate;
      jwt-secret: 9287a33a455a429fb737edc53bdac483
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: trackyourpacks@gmail.com
    password: tracking123!
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
logging:
  level:
    org:
      hibernate: DEBUG
