security:
  jwt:
    token:
      expire-length: 3600000
      auth-login-url: /users/authenticate;
      jwt-secret: xxx
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxx
    password: xxx
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
logging:
  level:
    org:
      hibernate: DEBUG
